import { Geist, Geist_Mono, Ubuntu } from "next/font/google";
import "./globals.css";
import Appbar from "./components/appbar.js";

const geistSans = Ubuntu({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "700",
});

const geistMono = Ubuntu({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Appbar />
        {children}
      </body>
    </html>
  );
}
